### PR TITLE
Adapt to current Apple Music format

### PR DESCRIPTION
**Pull request by reosarevok**
Changes to work around hydration and AppleMusic's event handlers, plus design changes.

### CODE REVIEW

**Comment by dufferzafar** [comment]
Screenshot please?

Which browsers have you tested it on?

**Comment by reosarevok** [comment]
Chrome and Firefox (the two I have).

Screenshot from 2020-08-24 08-21-48

I only just saw there was already one PR for this. If that one works too, you can just merge that one if you prefer, I won't feel bad :) I do feel standard JS for waiting for the hydration might be better than adding an extra requirement, personally, but might not be a big deal.

**Comment by dufferzafar** [comment]
I remember the your handle from the metabrainz IRC. So I'll just merge this. :sweat_smile:

**Comment by damienmauchamp** [comment]
Artwork not working when you are logged in. Should be :

```javascript
var srcset = left.getElementsByClassName('media-artwork-v2__image')[0].getAttribute('srcset');
```

**Comment by reosarevok** [comment]
Hmm, I don't have an account so I didn't know that :) Feel free to PR, especially if there's a good way to figure out which of the two it should be by looking at the code!

**Comment by damienmauchamp** [comment]
Fixed it, see #28

**Pull request merged**
