### PR TITLE
Uncaught TypeError fix + music.apple.com fix

### PR DESCRIPTION
**Pull request by damienmauchamp**
"Uncaught TypeError: Cannot read property 'slice' of undefined" fix.

Error when trying to get the artwork.

### CODE REVIEW

**Comment by dufferzafar** [comment]
@augustjane will you be able to review this?

**Comment by navrudh** [comment]
I had a problem with remix albums like https://music.apple.com/us/album/dont-let-me-down-feat-daya-remixes-ep/1134092126.

Track names are all the same i.e. the [] braces are omitted.

**Comment by damienmauchamp** [comment]
> I had a problem with remix albums like https://music.apple.com/us/album/dont-let-me-down-feat-daya-remixes-ep/1134092126.
> 
> Track names are all the same i.e. the `[]` braces are omitted.
> 
> The full track name is present in the `trackCensoredName` field

I've just fixed it

**Comment by chuckkahn** [comment]
Where's the MB button?  I don't see it.  https://imgur.com/a/edaDrii

**Comment by damienmauchamp** [comment]
> Where's the MB button? I don't see it. https://imgur.com/a/edaDrii

Should be at the under the tracklist.
image

Make sure you get the latest version until it gets merged.
[MB-Import-From-iTunes.user.js](https://github.com/damienmauchamp/Userscripts/blob/patch-1/MB-Import-From-iTunes.user.js)

**Comment by dufferzafar** [comment]
Closing in favour of #27

**Pull request closed without merging**
